"""create order tables

Revision ID: 318ba3d943b9
Revises: 
Create Date: 2025-04-29 10:57:55.033461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '318ba3d943b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sight_ticket')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sight_ticket',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('desc', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('price', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('discount', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('total', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remain', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expire_date', sa.DATE(), nullable=True),
    sa.Column('return_policy', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('sight_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
