"""add sight and sight_profile models

Revision ID: cc8cbbe2d008
Revises: 318ba3d943b9
Create Date: 2025-04-29 16:26:45.436966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc8cbbe2d008'
down_revision: Union[str, None] = '318ba3d943b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sight_id', table_name='sight_profile')
    op.drop_table('sight_profile')
    op.drop_table('sight_ticket')
    op.drop_table('sight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sight',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('desc', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('main_img', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('banner_img', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('score', mysql.FLOAT(), server_default=sa.text("'5'"), nullable=True),
    sa.Column('min_price', mysql.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('province', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('area', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('town', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('is_top', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('is_hot', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('is_valid', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sight_ticket',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('desc', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('price', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('discount', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('total', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remain', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expire_date', sa.DATE(), nullable=True),
    sa.Column('return_policy', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('sight_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sight_profile',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('img', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('explain', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('open_time', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('tel', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('level', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('tags', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('attention', mysql.LONGTEXT(), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('sight_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('sight_id', 'sight_profile', ['sight_id'], unique=True)
    # ### end Alembic commands ###
